[package]
name = "image-grid-server"
version = "0.2.4"
edition = "2024"
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
image-grid-core = { path = "../image-grid-core" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
uuid.workspace = true

[dev-dependencies]
http-body-util = "0.1"
tempfile.workspace = true
tower = { version = "0.5", features = ["util"] }
